# Generated by Django 3.2 on 2021-05-18 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import investapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='pending', max_length=1)),
                ('amount', models.TextField(default='', max_length=6)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_url', models.CharField(default=investapp.models.random_string, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=14)),
                ('alt_phone_number', models.CharField(blank=True, max_length=14)),
                ('profile_pic_url', models.CharField(blank=True, max_length=14)),
                ('refferer', models.TextField(default='', max_length=20)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicce', models.TextField(max_length=20)),
                ('amount', models.TextField(max_length=20)),
                ('earnings', models.TextField(max_length=20)),
                ('phone_number', models.TextField(max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
