# Generated by Django 3.2 on 2021-05-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investiments',
            name='invest_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investiments',
            name='percent',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='investiments',
            name='period',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='investiments',
            name='username',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
