# Generated by Django 3.2 on 2021-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0002_auto_20210519_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investiments',
            name='username',
            field=models.TextField(max_length=20),
        ),
    ]
