# Generated by Django 3.2 on 2021-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0003_alter_investiments_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investiments',
            name='percent',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='investiments',
            name='period',
            field=models.TextField(default=0),
        ),
    ]
