# Generated by Django 3.2 on 2021-05-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0004_auto_20210519_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investiments',
            name='username',
        ),
    ]
