# Generated by Django 3.2 on 2021-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0005_remove_investiments_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='investiments',
            name='status',
            field=models.TextField(blank=True, default='pending'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_balance',
            field=models.TextField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invest_balance',
            field=models.TextField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reg_fee',
            field=models.TextField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='investiments',
            name='invest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investiments',
            name='percent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='investiments',
            name='period',
            field=models.TextField(blank=True, default=''),
        ),
    ]
