# Generated by Django 3.2 on 2021-05-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0006_auto_20210519_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='investiments',
            name='control_balance',
            field=models.TextField(default=0, max_length=20),
        ),
    ]
